config/routes.rb
Rails.application.routes.draw do
  resources :crawls
  root :to => "crawls#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crawl.rb
class Crawl < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController
  before_action :set_crawl, only: [:show, :edit, :update, :destroy]

  # GET /crawls
  # GET /crawls.json
  def index
    @crawls = Crawl.all
  end

  # GET /crawls/1
  # GET /crawls/1.json
  def show
    registration = Crawl.find(1).reg_no
    # @crawls = Crawl.all
  end

  # GET /crawls/new
  def new
    @crawl = Crawl.new
  end

  # GET /crawls/1/edit
  def edit
  end

  # POST /crawls
  # POST /crawls.json
  def create
    @crawl = Crawl.new(crawl_params)

    respond_to do |format|
      if @crawl.save
        format.html { redirect_to @crawl, notice: 'Crawl was successfully created.' }
        format.json { render :show, status: :created, location: @crawl }
      else
        format.html { render :new }
        format.json { render json: @crawl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawls/1
  # PATCH/PUT /crawls/1.json
  def update
    respond_to do |format|
      if @crawl.update(crawl_params)
        format.html { redirect_to @crawl, notice: 'Crawl was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawl }
      else
        format.html { render :edit }
        format.json { render json: @crawl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawls/1
  # DELETE /crawls/1.json
  def destroy
    @crawl.destroy
    respond_to do |format|
      format.html { redirect_to crawls_url, notice: 'Crawl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawl
      @crawl = Crawl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawl_params
      params.require(:crawl).permit(:reg_no, :name, :dob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawls_helper.rb
module CrawlsHelper

require 'rubygems'
require 'nokogiri'
require "base64"
require 'open-uri'
require 'pry'

def get_image(reg_no)
doc = Nokogiri::HTML(open("http://coe1.annauniv.edu/home/"))
doc.css('#login_stu').each do |link|
	url = link.css('img')[0].first[1]
	return url
end
end
	# value = Base64.decode64(url['data:image/png;base64,'.length .. -1])
# 	File.open('test1.png', 'wb') { |f| f.write(value) }
# end
# 	File.open('test1.png', 'r') do|f|
end

app/views/crawls/_form.html.erb
<%= form_with(model: crawl, local: true) do |form| %>
  <% if crawl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crawl.errors.count, "error") %> prohibited this crawl from being saved:</h2>

      <ul>
      <% crawl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crawls/edit.html.erb
<h1>Editing Crawl</h1>

<%= render 'form', crawl: @crawl %>

<%= link_to 'Show', @crawl %> |
<%= link_to 'Back', crawls_path %>

app/views/crawls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crawls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crawls.each do |crawl| %>
      <tr>
        <td><%= crawl.id %></td>
        <td><%= crawl.name %></td>
        <td><%= crawl.reg_no %></td>
        <td><%= crawl.dob %></td>
        <td><%= link_to 'Show', crawl %></td>
        <td><%= link_to 'Edit', edit_crawl_path(crawl) %></td>
        <td><%= link_to 'Destroy', crawl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crawl', new_crawl_path %>

app/views/crawls/new.html.erb
<h1>New Crawl</h1>

<%= form_for @crawl , method: :post do |f| %>
<%= f.label "Registration Number" %>
<%= f.text_field(:reg_no) %>
<%= f.label "Name" %>
<%= f.text_field(:name) %>
<%= f.label "Date of Birth" %>
<%= f.text_field(:dob) %>
<br/><br/>
<%= f.submit "Submit" %>
<% end %>

<%#= render 'form', crawl: @crawl %>

<%#= link_to 'Back', crawls_path %>

app/views/crawls/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<%= link_to 'Edit', edit_crawl_path(@crawl) %> |
<%= link_to 'Back', crawls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crawling</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>